services:
  discordbot:
    container_name: ${DISCORDBOT_CONTAINER_HOST}
    hostname: ${DISCORDBOT_HOST}
    env_file: .env
    tty: true
    build:
      context: .
      dockerfile: ./docker/discordbot/Dockerfile
    volumes:
      - ./src/discordbot:/src